import { useState, useEffect } from "react";
import { Variant } from "@/types";
import { explainVariant } from "@/lib/llm";

interface ExplainableAIModuleProps {
  variant: Variant;
}

export function ExplainableAIModule({ variant }: ExplainableAIModuleProps) {
  const [explanation, setExplanation] = useState<string>("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadExplanation() {
      setLoading(true);
      try {
        const text = await explainVariant(variant);
        setExplanation(text);
      } catch (err) {
        setExplanation("Unable to generate AI explanation at this time.");
      } finally {
        setLoading(false);
      }
    }
    loadExplanation();
  }, [variant]);

  // Parse sections if they exist in the LLM response
  // Matches "1. SECTION NAME:" or "SECTION NAME:"
  const sections = explanation.split(/\n(?=\d?\.?\s?[A-Z\s]{5,}:)/).filter(s => s.trim().length > 0);

  return (
    <div className="bg-surface-container-lowest rounded-2xl border border-outline-variant/10 overflow-hidden shadow-lg animate-in fade-in zoom-in-95 duration-500">
      <div className="p-4 bg-primary/5 border-b border-outline-variant/10 flex justify-between items-center">
        <h3 className="text-[10px] font-black uppercase tracking-[0.3em] text-primary flex items-center gap-2">
          <span className="material-symbols-outlined text-sm">psychology</span>
          5. Explainable AI Module
        </h3>
        {loading && (
          <div className="flex items-center gap-2">
            <div className="w-1 h-1 rounded-full bg-primary animate-bounce [animation-delay:-0.3s]" />
            <div className="w-1 h-1 rounded-full bg-primary animate-bounce [animation-delay:-0.15s]" />
            <div className="w-1 h-1 rounded-full bg-primary animate-bounce" />
          </div>
        )}
      </div>
      
      <div className="p-6">
        {loading ? (
          <div className="space-y-4">
            <div className="h-4 bg-surface-container rounded-lg w-3/4 animate-pulse" />
            <div className="h-4 bg-surface-container rounded-lg w-full animate-pulse" />
            <div className="h-4 bg-surface-container rounded-lg w-5/6 animate-pulse" />
          </div>
        ) : (
          <div className="space-y-6">
            <div className="flex items-start gap-4 p-4 bg-surface-container-low rounded-xl border border-outline-variant/10">
              <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center shrink-0">
                <span className="material-symbols-outlined text-primary text-xl">genetics</span>
              </div>
              <div>
                <p className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest mb-1">Variant Target</p>
                <p className="text-sm font-bold text-primary">{variant.gene} {variant.mutation}</p>
                 <p className="text-[10px] text-on-surface-variant mt-0.5">Phenotype Assessment: {variant.risk}</p>
              </div>
            </div>

            <div className="grid gap-6">
              {sections.length > 1 ? (
                sections.map((section, idx) => {
                  const colonIdx = section.indexOf(":");
                  const titleRaw = colonIdx !== -1 ? section.substring(0, colonIdx) : "";
                  const content = colonIdx !== -1 ? section.substring(colonIdx + 1) : section;
                  
                  // Clean title (remove numbers like "1. ")
                  const title = titleRaw.replace(/^\d+\.\s*/, "").trim();

                  return (
                    <div key={idx} className="space-y-2 group">
                      <div className="flex items-center gap-2">
                        <div className="w-1.5 h-1.5 rounded-full bg-primary/40 group-hover:bg-primary transition-colors" />
                        <h4 className="text-[10px] font-black text-on-surface-variant uppercase tracking-widest">{title || `Observation ${idx + 1}`}</h4>
                      </div>
                      <p className="text-xs leading-relaxed text-on-surface/80 pl-3.5 border-l border-outline-variant/20 ml-0.5 whitespace-pre-wrap">
                        {content.trim()}
                      </p>
                    </div>
                  );
                })
              ) : (
                <p className="text-xs leading-relaxed text-on-surface/80 whitespace-pre-wrap">{explanation}</p>
              )}
            </div>

            <div className="pt-4 border-t border-outline-variant/10">
              <div className="flex items-center gap-2 text-[10px] text-on-surface-variant italic">
                <span className="material-symbols-outlined text-sm">verified_user</span>
                Human-readable medical reasoning generated by PharmaGuard Core LLM
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
